app/question_templates/__init__.py
from flask import Blueprint

bp = Blueprint("question_templates", __name__)

from app.question_templates import routes

app/question_templates/routes.py
from flask import jsonify, render_template, request

from app.question_templates import bp
from app.extensions import db

from app.models.template import Template
from app.models.question import Question

@bp.route("/", methods=["GET"])
def index():
    templates = Template.query.all()
    return render_template("question_templates.html", templates=templates)

@bp.route("/<template_id>", methods=["GET"])
def template(template_id):
    # Try to get template from database
    template = Template.query.filter_by(id=template_id).first()

    # If template does not exist, return 404
    if template is None:
        return render_template("404.html"), 404
    
    return render_template("template.html", template=template)

@bp.route("/get_template", methods=["GET"])
def get_template():
    # Get template ID from request
    template_id = request.args.get("id")

    # Ensure that template ID is present
    if template_id is None:
        return "No template ID specified", 400
    
    # Try to get template from database
    template = Template.query.filter_by(id=template_id).first()

    # If template does not exist, return 404
    if template is None:
        return "Template does not exist", 404

    # Structure response
    response = {
        "id": template.id,
        "name": template.name,
        "question_ids": [question.id for question in template.questions]
    }
    
    return jsonify(response), 200

@bp.route("/<template_id>/delete_question", methods=["DELETE"])
def delete_question(template_id):
    # Get question ID from request
    question_id = request.args.get("id")

    # Ensure that question ID is present
    if question_id is None:
        return "No question ID specified", 400

    # Try to get template from database
    template = Template.query.filter_by(id=template_id).first()

    # If template does not exist, return 404
    if template is None:
        return "Template does not exist", 404
    
    # Try to get question from database
    question = Question.query.filter_by(id=question_id).first()

    # If question does not exist, return 404
    if question is None:
        return "Question does not exist", 404
    
    # Remove question from template
    try:
        template.questions.remove(question)
        db.session.commit()
    except ValueError:
        return "Question not found in template", 404

    return "Question removed from template", 200

@bp.route("/delete", methods=["DELETE"])
def delete_template():
    # Get template ID from request
    template_id = request.args.get("id")

    # Ensure that template ID is present
    if template_id is None:
        return "No template ID specified", 400
    
    # Try to get template from database
    template = Template.query.filter_by(id=template_id).first()

    # If template does not exist, return 404
    if template is None:
        return "Template does not exist", 404
    
    # Delete template
    db.session.delete(template)
    db.session.commit()

    return "Template deleted", 200

@bp.route("/add", methods=["POST"])
def add_to_template():
    """ Adds selected questions to a template.
        If template does not exist, creates a new template.
    """

    # Get POST JSON data
    data = request.get_json()

    # Reject if no JSON data is found, or data is malformed
    if data is None or "template" not in data or "questions" not in data:
        return "Bad Request", 400
    
    # Get template name and questions
    template_id = data["template"]
    questions = data["questions"]

    # Ensure that template ID is a string
    if not isinstance(template_id, str):
        return "Template ID should be a string!", 400

    # Ensure that questions is a list
    if not isinstance(questions, list):
        return "Questions should be an array!", 400

    # Ensure that questions is not empty
    if len(questions) == 0:
        return "No questions selected!", 400

    # Get template from database and create new template if it does not exist
    template = Template.query.filter_by(id=template_id).first()
    if template is None:
        template = Template(name=template_id)
        db.session.add(template)
    
    # Add questions to template
    template_questions = set(template.questions)  # Convert to set to remove duplicates

    for question in questions:
        # Ensure question is a valid question
        queried_question = Question.query.filter_by(id=question).first()
        if not queried_question:
            return f"Question {question} does not exist", 400

        # Add question to template
        template_questions.add(queried_question)

    template.questions = list(template_questions)
    db.session.commit()

    return "Questions added to template", 200

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    {% if title %}
    <title>{{ title }} - RMSS Question Bank</title>
    {% else %}
    <title>RMSS Question Bank</title>
    {% endif %}

    <!-- Import EditorJS and it's modules -->
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/table@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/image@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/editorjs-paragraph-with-alignment@latest"></script>

    <!-- JQuery and Chosen for dropdown searching -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/chosen.jquery.min.js') }}"></script>

    <!-- Import other scripts the html may need -->
    {% block scripts %} {% endblock %}

    <!-- CSS -->
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/chosen.min.css') }}"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <!-- NavBar -->
    <ul class="navbar-custom">
      <li class="navbar-custom"><a href="#" class="active">Question Bank</a></li>
      <li class="navbar-custom"><a href="{{ url_for('main.index') }}">Add Question</a></li>
      <li class="navbar-custom"><a href="{{ url_for('questions_frontend.search_question') }}">Add to Book</a></li>
      <li class="navbar-custom"><a href="{{ url_for('topics.edit_topics') }}">Edit Topics</a></li>
      <li class="navbar-custom"><a href="{{ url_for('question_templates.index') }}">Templates</a></li>
    </ul>

    {% block content %} {% endblock %}
  </body>
</html>

app/templates/edit_question.html
{% extends "base.html" %}
{% block title %}Edit Question{% endblock %}

{% block content %}
    <h1 style="text-align: center;">Editing {{ question.id }}</h1>
    <div class="question-editor">
        <div id="question_editor" class="editorjs"></div>
        <div id="answer_editor" class="editorjs"></div>
        <input type="submit" class="button" id="save-btn" value="Save"/>
    </div>
    <script>
        const editor_question = new EditorJS({
            holder: "question_editor",
            minHeight: 100,
            tools: {
                paragraph: {
                    class: Paragraph,
                    inlineToolbar: ["bold", "italic"],
                },
                table: {
                    class: Table,
                    inlineToolbar: true,
                },
                image: {
                    class: ImageTool,
                    config: {
                        endpoints: {
                            byFile: "/api/image/upload_file",
                            byUrl: "/api/image/upload_url",
                        },
                    },
                    inlineToolbar: true,
                },
            },
            {% autoescape false %}
            data: {{ question.content | replace("False", "false") | replace("True", "true") }},
            {% endautoescape %}
        });

        // EditorJS for answer
        const editor_answer = new EditorJS({
            holder: "answer_editor",
            minHeight: 50,
            tools: {
                paragraph: {
                    class: Paragraph,
                    inlineToolbar: ["bold", "italic"],
                },
                table: {
                    class: Table,
                    inlineToolbar: true,
                },
                image: {
                    class: ImageTool,
                    config: {
                        endpoints: {
                            byFile: "/api/image/upload_file",
                            byUrl: "/api/image/upload_url",
                        },
                    },
                    inlineToolbar: true,
                },
            },
            {% autoescape false %}
            data: {{ question.answer | replace("False", "false") | replace("True", "true") }},
            {% endautoescape %}
        });

        // Alert user if EditorJS fails to load
        editor_question.isReady
            .then(() => {
                console.log("EditorJS is ready to work!");
            })
            .catch((reason) => {
                console.log("EditorJS initialization failed because of ", reason);
            });
        
        editor_answer.isReady
            .then(() => {
                console.log("EditorJS is ready to work!");
            })
            .catch((reason) => {
                console.log("EditorJS initialization failed because of ", reason);
            });

        // Save button
        document.getElementById("save-btn").addEventListener("click", async () => {
            let response = {"id": "{{ question.id }}"};

            await editor_question.save().then((outputData) => {
                response["content"] = outputData;
            }).catch((error) => {
                console.log("Saving failed: ", error);
            });

            await editor_answer.save().then((outputData) => {
                response["answer"] = outputData;
            }).catch((error) => {
                console.log("Saving failed: ", error);
            });

            // Send data to server
            var xhr = new XMLHttpRequest();
            xhr.responseType = "json";
            xhr.open("POST", "/api/question/edit", true);
            xhr.setRequestHeader("Content-Type", "application/json");

            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4 && xhr.status === 200) {
                    let url = "/questions/search"

                    let section = new URLSearchParams(window.location.search).get("section");
                    let category = new URLSearchParams(window.location.search).get("category");

                    if (section !== null) {
                        url += "?section=" + section;
                    }

                    if (category !== null) {
                        if (section !== null) {
                            url += "&category=" + category;
                        } else {
                            url += "?category=" + category;
                        }
                    }

                    location.href = url;
                }

                if (xhr.readyState === 4 && xhr.status !== 200) {
                    try {
                        alert("Failed to save question!\nError: " + xhr.response["message"]);
                    } catch (e) {
                        alert("Error connecting to server! Please try again later.");
                    }
                }
            };

            xhr.send(JSON.stringify(response));
        });
    </script>
{% endblock %}

app/templates/edit_topics.html
{% extends "base.html" %}
{% block title %}Edit Topics{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/edit_topics.js') }}"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css">
{% endblock %}

{% block content %}
    <h1 style="text-align: center;">Edit Topics</h1>

    <div style="width: 80%; margin: auto;">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Level</th>
                    <th>Subject</th>
                    <th>Topic</th>
                    <th>Options</th>
                </tr>
            </thead>

            <tbody>
                {% for category in categories %}
                <tr row_id="{{ category.id }}">
                    <td><div class="row_data" edit_type="click" col_name="level">{{ category.level }}</div></td>
                    <td><div class="row_data" edit_type="click" col_name="subject">{{ category.subject }}</div></td>
                    <td><div class="row_data" edit_type="click" col_name="topic">{{ category.topic }}</div></td>

                    <td>
                        <span class="btn_edit"><a href="#" class="btn btn-primary" row_id="{{ category.id }}">Edit</a></span>

                        <span class="btn_save"><a href="#" class="btn btn-primary" row_id="{{ category.id }}">Save</a></span>
                        <span class="btn_delete"><a href="#" class="btn btn-danger" row_id="{{ category.id }}">Delete</a></span>
                        <span class="btn_cancel"><a href="#" class="btn btn-primary" row_id="{{ category.id }}">Cancel</a></span>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div style="margin: auto; text-align: center;">
        <label for="level">Level</label>
        <input type="text" id="level" placeholder="E.g Secondary 1">

        <label for="subject">Subject</label>
        <input type="text" id="subject" placeholder="E.g Math">

        <label for="topic">Topic</label>
        <input type="text" id="topic" placeholder="E.g Functions and Graphs" size="50">

        <button id="btn_add_topic">Add Topic</button>
    </div>
{% endblock %}

app/templates/error.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>400 Bad Request</title>
</head>
<body>
    <h1>Error!</h1>
    <p>Details: {{ error }}</p>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block title %}Add Question{% endblock %}

{% block scripts %}
<script
    src="{{ url_for('static', filename='js/index.js') }}"
    type="module"
></script>
{% endblock %}

{% block content %}
    <h1 style="text-align: center">Add Question</h1>
    <div class="question-editor">
        <div class="question-ids">
            <label for="qn-school">School</label>
            <input type="text" id="qn-school" maxlength="10" />
        
            <label for="qn-level">Level</label>
            <select id="qn-level">
                <option value="P1">Primary 1</option>
                <option value="P2">Primary 2</option>
                <option value="P3">Primary 3</option>
                <option value="P4">Primary 4</option>
                <option value="P5">Primary 5</option>
                <option value="P6">Primary 6</option>
                <option value="S1">Secondary 1</option>
                <option value="S2">Secondary 2</option>
                <option value="S3">Secondary 3</option>
                <option value="S4">Secondary 4</option>
                <option value="J1">JC 1</option>
                <option value="J2">JC 2</option>
            </select>
        
            <label for="qn-test">Test</label>
            <input type="text" id="qn-test" maxlength="5" />

            <br>
        
            <label for="qn-year">Year</label>
            <input
                type="number"
                id="qn-year"
                value="2023"
                onkeypress="return (event.charCode !=8 && event.charCode ==0 || (event.charCode >= 48 && event.charCode <= 57))"
            />
        
            <label for="qn-number">Question No.</label>
            <input
                type="number"
                id="qn-number"
                style="width: 50px"
                value="1"
                onkeypress="return (event.charCode !=8 && event.charCode ==0 || (event.charCode >= 48 && event.charCode <= 57))"
            />
        
            <label for="qn-section">Section</label>
            <select id="qn-section">
                <option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
            </select>

            <br>
        
            <label for="qn-category">Category</label>
            <select id="qn-category">
                {% for category in categories %}
                <option value="{{ category.id }}">
                    {{ category.topic }} ({{ category.level }}, {{ category.subject }})
                </option>
                {% endfor %}
            </select>
        </div>
    
        <div class="editorjs" id="editorjs_question"></div>
        <div class="editorjs" id="editorjs_answer"></div>
        <input type="submit" class="button" id="save-btn" value="Save"/>
    </div>
{% endblock %}

app/templates/list_questions.html
{% extends "search_question.html" %}
{% block title %}Add Question{% endblock %}

{% block questions %}
    {% for question in questions %}
        <div
            class="question-editor"
            id="{{ question.id }}"
            onclick="on_select(this.id)"
            style="cursor: pointer;"
        >
            <div id="{{ question.id }}">
                <p>Question ID: {{ question.id }}</p>
                <p>
                    Category: {{ question.category.topic }} ({{ question.category.level }}, {{ question.category.subject }})
                </p>
            </div>

            <div id="question-{{ question.id }}" class="editorjs"></div>
            <div id="answer-{{ question.id }}" class="editorjs"></div>
            <div style="display: inline;">
              <button
                  onclick="event.stopPropagation(); on_edit('{{ question.id }}');"
                  class="button"
                  id="edit-btn"
                  style="display: inline;"
              >
                  Edit
              </button>
              <button
                  onclick="event.stopPropagation(); on_delete('{{ question.id }}');"
                  class="button"
                  id="delete-btn"
                  style="display: inline;"
              >
                Delete
              </button>
            </div>
        </div>
        <script>
            new EditorJS({
              holder: "question-{{ question.id }}",
              minHeight: 50,
              tools: {
                  paragraph: {
                    class: Paragraph,
                    inlineToolbar: ["bold", "italic"],
                  },
                  table: {
                    class: Table,
                    inlineToolbar: true,
                  },
                  image: {
                    class: ImageTool,
                    config: {
                      endpoints: {
                        byFile: "/api/image/upload_file",
                        byUrl: "/api/image/upload_url",
                      },
                    },
                    inlineToolbar: true,
                  },
                },
              {% autoescape false %}
              data: {{ question.content | replace("False", "false") | replace("True", "true") }},
              {% endautoescape %}
              readOnly: true
            });
        </script>
        <script>
            new EditorJS({
                holder: "answer-{{ question.id }}",
                minHeight: 20,
                tools: {
                  paragraph: {
                    class: Paragraph,
                    inlineToolbar: ["bold", "italic"],
                  },
                  table: {
                    class: Table,
                    inlineToolbar: true,
                  },
                  image: {
                    class: ImageTool,
                    config: {
                      endpoints: {
                        byFile: "/api/image/upload_file",
                        byUrl: "/api/image/upload_url",
                      },
                    },
                    inlineToolbar: true,
                  },
                },
                {% autoescape false %}
                data: {{ question.answer | replace("False", "false") | replace("True", "true") }},
                {% endautoescape %}
                readOnly: true
            });
        </script>
    {% endfor %}
{% endblock %}

app/templates/question_templates.html
{% extends "base.html" %}
{% block title %}Templates{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/question_templates.js') }}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css">
{% endblock %}

{% block content %}
    <h1 style="text-align: center;">Templates</h1>

    <div class="template-list">
        {% for template in templates %}
            <div class="template-card">
                <div style="float: left;">
                    <h2>{{ template.name }}</h2>
                    <p>Questions: {{ template.questions | length }}</p>
                </div>

                <div style="float: right;">
                    <button class="btn btn-primary" onclick="templateCardClicked(this.id)" id="{{ template.id }}">Edit</button>
                    <button class="btn btn-danger" onclick="deleteTemplateClicked(this.id)" id="{{ template.id }}">Delete</button>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/search_question.html
{% extends "base.html" %}
{% block title %}Search{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/questions.js') }}" type="module"></script>
{% endblock %}

{% block content %}
    <h1 style="text-align: center;">Search for Questions</h1>

    <div class="question_search">
        <label for="section-select">Section</label>
        <select id="section-select" data-placeholder=" ">
            <option value="">None</option>
            <option value="A">A</option>
            <option value="B">B</option>
            <option value="C">C</option>
        </select>

        <label for="category-select">Category</label>
        <select id="category-select" data-placeholder=" ">
            <option value="">None</option>
            {% for category in categories %}
                <option value="{{ category.id }}">{{ category.topic }} ({{ category.subject }}, {{ category.level }})</option>
            {% endfor %}
        </select>

        <button onclick="" class="button" id="search-btn"><i class="fa fa-search"></i></button>
    </div>

    <div class="selected-questions">
        <h2 style="text-align: center;" id="sel-qns-h2">0 Selected Question(s)</h2>

        <button class="button" id="clear-qns-btn">Clear Questions</button>
        <button class="button" id="export-btn">Add to Word</button>
        <button class="button" id="template-btn">Add to Template</button>
        <button class="button" id="import-template-btn">Import from Template</button>

        <select id="template-select" data-placeholder=" ">
            <option value="">None</option>
            {% for template in templates %}
                <option value="{{ template.id }}">{{ template.name }}</option>
            {% endfor %}
        </select>

        <div id="selected-questions-list"></div>
    </div>
    <div id="toggle-sel-qns">
        <p>Selected</p>
    </div>

    <script>
        // Select section & category based on URL parameters
        let urlParams = new URLSearchParams(window.location.search);
        let section = urlParams.get('section');
        let category = urlParams.get('category');

        if (section) {
            document.getElementById('section-select').value = section;
        }

        if (category) {
            document.getElementById('category-select').value = category;
        }
    </script>

    {% block questions %}
    {% endblock %}
{% endblock %}

app/templates/template.html
{% extends "base.html" %}
{% block title %}{{ template.name }}{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/question_templates.js') }}"></script>
{% endblock %}

{% block content %}
    <h1 style="text-align: center;">Template: {{ template.name }}</h1>
    <button class="button" id="delete-btn" onclick="deleteTemplateClicked('{{ template.id }}')">Delete Template</button>
    <div class="template-questions">
        {% for question in template.questions %}
            <div
                class="question-editor"
                id="{{ question.id }}"
            >
                <div id="{{ question.id }}">
                    <p>Question ID: {{ question.id }}</p>
                    <p>
                        Category: {{ question.category.topic }} ({{ question.category.level }}, {{ question.category.subject }})
                    </p>
                </div>

                <div id="question-{{ question.id }}" class="editorjs"></div>
                <div id="answer-{{ question.id }}" class="editorjs"></div>
                  <button
                      onclick="event.stopPropagation(); removeQuestionClicked('{{ question.id }}', '{{ template.id }}');"
                      class="button"
                      id="delete-btn"
                      style="display: inline; width: 180px;"
                  >
                    Remove from Template
                  </button>
                </div>
            </div>
            <script>
                new EditorJS({
                  holder: "question-{{ question.id }}",
                  minHeight: 50,
                  tools: {
                      paragraph: {
                        class: Paragraph,
                        inlineToolbar: ["bold", "italic"],
                      },
                      table: {
                        class: Table,
                        inlineToolbar: true,
                      },
                      image: {
                        class: ImageTool,
                        config: {
                          endpoints: {
                            byFile: "/api/image/upload_file",
                            byUrl: "/api/image/upload_url",
                          },
                        },
                        inlineToolbar: true,
                      },
                    },
                  {% autoescape false %}
                  data: {{ question.content | replace("False", "false") | replace("True", "true") }},
                  {% endautoescape %}
                  readOnly: true
                });
            </script>
            <script>
                new EditorJS({
                    holder: "answer-{{ question.id }}",
                    minHeight: 20,
                    tools: {
                      paragraph: {
                        class: Paragraph,
                        inlineToolbar: ["bold", "italic"],
                      },
                      table: {
                        class: Table,
                        inlineToolbar: true,
                      },
                      image: {
                        class: ImageTool,
                        config: {
                          endpoints: {
                            byFile: "/api/image/upload_file",
                            byUrl: "/api/image/upload_url",
                          },
                        },
                        inlineToolbar: true,
                      },
                    },
                    {% autoescape false %}
                    data: {{ question.answer | replace("False", "false") | replace("True", "true") }},
                    {% endautoescape %}
                    readOnly: true
                });
            </script>
        {% endfor %}
    </div>
{% endblock %}